### ISSUE TITLE
Maybe there is something wrong

### ISSUE THREAD

**Issue by Jiaqi-Min** [LinBuyu/DSfdr#1]
Thanks for your working.This package is very useful. I found that Rstudio cannot download it when I want to install the "DSfdr" package by using "devtools::install_github("Jeremy690/DSfdr") ".
But it can be installed by using  "devtools ::install_github("Jeremy690/DSfdr/DSfdr") " without a hitch.

**Comment by Jeremy690** [comment]
Yes, you're right. Have fixed it.
